---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r Loading_Data, echo=TRUE}
#unzip and read csv
unzip("activity.zip")
activity_data<-read.csv("activity.csv")

#Format date column into a date
activity_data$date<-as.Date(activity_data$date)
```

## What is mean total number of steps taken per day?
```{r meanofsteps, echo=TRUE}
#aggregate the steps by date
sum_steps<-aggregate(steps~date, data=activity_data, sum)

hist(sum_steps$steps, main="Total Number of Steps taken per Day")

#calculate the mean of the total steps
mean(sum_steps$steps)

#calculate the media of the total steps
median(sum_steps$steps)
```

## What is the average daily activity pattern?
```{r}
#aggregate the steps by interval mean
mean_interval<-aggregate(steps~interval, data=activity_data, mean)
plot(mean_interval$steps~mean_interval$interval,type="l", main="Average Number of Steps taken")

print("interval with max value:")
mean_interval[which.max(mean_interval$steps),]$interval
```


## Imputing missing values
```{r}
#total number of rows that have NA Values
nrow(activity_data)-sum(complete.cases(activity_data))
```

Strategy for filling in missing data shall be using the mean for that interval

```{r}
new_data<-activity_data
for(i in 1:nrow(new_data)){
  if(is.na(new_data[i,]$steps)){
    tempo_row<-subset(mean_interval, mean_interval$interval==new_data[i,]$interval)
    new_data[i,]$steps<-tempo_row$steps
    }
}

#aggregate the steps by date
new_sum_steps<-aggregate(steps~date, data=new_data, sum)

hist(new_sum_steps$steps, main="Total Number of Steps taken per Day")

#calculate the mean of the total steps
mean(new_sum_steps$steps)

#calculate the media of the total steps
median(new_sum_steps$steps)
```

## Are there differences in activity patterns between weekdays and weekends?
```{r}
new_data$day<-ifelse(weekdays(as.Date(new_data$date))=="Saturday","weekend",ifelse(weekdays(as.Date(new_data$date))=="Sunday","weekend","weekday"))
```

